In [5]:
import pandas as pd

In [6]:
full_data = pd.read_csv("la_liga_data_2010_2026.csv")

In [7]:
print(full_data.head())

   rk        squad  mp   w  d   l   gf  ga  gd  pts  ...  \
0   1    Barcelona  38  30  6   2   95  21  74   96  ...
1   2  Real Madrid  38  29  5   4  102  33  69   92  ...
2   3     Valencia  38  21  8   9   64  44  20   71  ...
3   4   Villarreal  38  18  8  12   54  44  10   62  ...
4   5      Sevilla  38  17  7  14   62  61   1   58  ...

          top_team_scorer      goalkeeper  \
0       Lionel Messi - 31   Víctor Valdés
1  Cristiano Ronaldo - 40   Iker Casillas
2    Roberto Soldado - 18  Vicente Guaita
3     Giuseppe Rossi - 18     Diego López
4     Álvaro Negredo - 20      Javi Varas

                                         notes season  xg  xga  xgd  xgd/90  \
0  → Champions League via Champions League win   2010 NaN  NaN  NaN     NaN
1         → Champions League via league finish   2010 NaN  NaN  NaN     NaN
2         → Champions League via league finish   2010 NaN  NaN  NaN     NaN
3         → Champions League via league finish   2010 NaN  NaN  NaN     NaN
4            → Europa League via league finish   2010 NaN  NaN  NaN     NaN

   games_left  projected_pts
0           0           96.0
1           0           92.0
2           0           71.0
3           0           62.0
4           0           58.0

[5 rows x 22 columns]

In [8]:
print(full_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rk               300 non-null    int64
 1   squad            300 non-null    object
 2   mp               300 non-null    int64
 3   w                300 non-null    int64
 4   d                300 non-null    int64
 5   l                300 non-null    int64
 6   gf               300 non-null    int64
 7   ga               300 non-null    int64
 8   gd               300 non-null    int64
 9   pts              300 non-null    int64
 10  pts/mp           300 non-null    float64
 11  attendance       204 non-null    float64
 12  top_team_scorer  300 non-null    object
 13  goalkeeper       300 non-null    object
 14  notes            151 non-null    object
 15  season           300 non-null    int64
 16  xg               160 non-null    float64
 17  xga              160 non-null    float64
 18  xgd              160 non-null    float64
 19  xgd/90           160 non-null    float64
 20  games_left       300 non-null    int64
 21  projected_pts    300 non-null    float64
dtypes: float64(7), int64(11), object(4)
memory usage: 51.7+ KB
None

In [9]:
print(full_data.tail(20))

     rk            squad  mp   w   d   l   gf  ga  gd  pts  ...  \
280   1        Barcelona  38  28   4   6  102  39  63   88  ...
281   2      Real Madrid  38  26   6   6   78  38  40   84  ...
282   3  Atlético Madrid  38  22  10   6   68  30  38   76  ...
283   4    Athletic Club  38  19  13   6   54  29  25   70  ...
284   5       Villarreal  38  20  10   8   71  51  20   70  ...
285   6            Betis  38  16  12  10   57  50   7   60  ...
286   7       Celta Vigo  38  16   7  15   59  57   2   55  ...
287   8   Rayo Vallecano  38  13  13  12   41  45  -4   52  ...
288   9          Osasuna  38  12  16  10   48  52  -4   52  ...
289  10         Mallorca  38  13   9  16   35  44  -9   48  ...
290  11    Real Sociedad  38  13   7  18   35  46 -11   46  ...
291  12         Valencia  38  11  13  14   44  54 -10   46  ...
292  13           Getafe  38  11   9  18   34  39  -5   42  ...
293  14         Espanyol  38  11   9  18   40  51 -11   42  ...
294  15           Alavés  38  10  12  16   38  48 -10   42  ...
295  16           Girona  38  11   8  19   44  60 -16   41  ...
296  17          Sevilla  38  10  11  17   42  55 -13   41  ...
297  18          Leganés  38   9  13  16   39  56 -17   40  ...
298  19       Las Palmas  38   8   8  22   40  61 -21   32  ...
299  20       Valladolid  38   4   4  30   26  90 -64   16  ...

                  top_team_scorer            goalkeeper  \
280       Robert Lewandowski - 27            Iñaki Peña
281            Kylian Mbappé - 31      Thibaut Courtois
282        Alexander Sørloth - 20             Jan Oblak
283             Oihan Sancet - 15            Unai Simón
284              Ayoze Pérez - 19           Diego Conde
285                      Isco - 9                Adrián
286           Borja Iglesias - 11        Vicente Guaita
287           Jorge de Frutos - 6       Augusto Batalla
288             Ante Budimir - 21        Sergio Herrera
289  Cyle Larin, Vedat Muriqi - 7         Dominik Greif
290           Mikel Oyarzabal - 9           Álex Remiro
291                Hugo Duro - 11  Giorgi Mamardashvili
292          Mauro Arambarri - 10           David Soria
293               Javi Puado - 12           Joan García
294                     Kiké - 13        Antonio Sivera
295         Cristhian Stuani - 11       Paulo Gazzaniga
296           Dodi Lukebakio - 11          Ørjan Nyland
297                 Dani Raba - 8       Marko Dmitrović
298              Fábio Silva - 10      Jasper Cillessen
299             Mamadou Sylla - 5       Karl Jakob Hein

                                     notes season    xg   xga   xgd  xgd/90  \
280   → Champions League via league finish   2024  91.5  41.9  49.5    1.30
281   → Champions League via league finish   2024  75.3  42.8  32.5    0.86
282   → Champions League via league finish   2024  64.6  33.4  31.2    0.82
283   → Champions League via league finish   2024  53.0  37.8  15.2    0.40
284   → Champions League via league finish   2024  64.8  44.4  20.4    0.54
285      → Europa League via league finish   2024  54.7  50.6   4.1    0.11
286      → Europa League via league finish   2024  54.2  43.4  10.9    0.29
287  → Conference League via league finish   2024  45.4  49.0  -3.5   -0.09
288                                    NaN   2024  44.0  53.7  -9.7   -0.25
289                                    NaN   2024  38.8  46.8  -8.1   -0.21
290                                    NaN   2024  42.5  43.9  -1.5   -0.04
291                                    NaN   2024  43.3  51.9  -8.6   -0.23
292                                    NaN   2024  36.8  46.2  -9.4   -0.25
293                                    NaN   2024  34.4  53.8 -19.4   -0.51
294                                    NaN   2024  42.8  47.0  -4.2   -0.11
295                                    NaN   2024  42.5  50.4  -8.0   -0.21
296                                    NaN   2024  42.7  47.4  -4.7   -0.12
297                              Relegated   2024  36.0  59.4 -23.4   -0.62
298                              Relegated   2024  36.3  66.8 -30.5   -0.80
299                              Relegated   2024  34.6  67.6 -33.0   -0.87

     games_left  projected_pts
280           0           88.0
281           0           84.0
282           0           76.0
283           0           70.0
284           0           70.0
285           0           60.0
286           0           55.0
287           0           52.0
288           0           52.0
289           0           48.0
290           0           46.0
291           0           46.0
292           0           42.0
293           0           42.0
294           0           42.0
295           0           41.0
296           0           41.0
297           0           40.0
298           0           32.0
299           0           16.0

[20 rows x 22 columns]

In [10]:
# Open data frame
df_2010_2011

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Attendance,Top Team Scorer,Goalkeeper,Notes
0,1,Barcelona,38,30,6,2,95,21,74,96,2.53,NaN,Lionel Messi - 31,Víctor Valdés,→ Champions League via Champions League win
1,2,Real Madrid,38,29,5,4,102,33,69,92,2.42,NaN,Cristiano Ronaldo - 40,Iker Casillas,→ Champions League via league finish
2,3,Valencia,38,21,8,9,64,44,20,71,1.87,NaN,Roberto Soldado - 18,Vicente Guaita,→ Champions League via league finish
3,4,Villarreal,38,18,8,12,54,44,10,62,1.63,NaN,Giuseppe Rossi - 18,Diego López,→ Champions League via league finish
4,5,Sevilla,38,17,7,14,62,61,1,58,1.53,NaN,Álvaro Negredo - 20,Javi Varas,→ Europa League via league finish
5,6,Athletic Club,38,18,4,16,59,55,4,58,1.53,NaN,Fernando Llorente - 18,Gorka Iraizoz,→ Europa League via league finish 1
6,7,Atlético Madrid,38,17,7,14,62,53,9,58,1.53,NaN,Sergio Agüero - 20,David de Gea,→ Europa League via league finish
7,8,Espanyol,38,15,4,19,46,55,-9,49,1.29,NaN,Dani Osvaldo - 13,Carlos Kameni,NaN
8,9,Osasuna,38,13,8,17,45,46,-1,47,1.24,NaN,Enrique Sola - 7,Ricardo,NaN
9,10,Sporting Gijón,38,11,14,13,35,42,-7,47,1.24,NaN,Diego Castro - 9,Juan Pablo Colinas,NaN
10,11,Málaga,38,13,7,18,54,68,-14,46,1.21,NaN,Salomón Rondón - 14,Willy Caballero,NaN
11,12,Racing Sant,38,12,10,16,41,56,-15,46,1.21,NaN,Markus Rosenberg - 9,Toño,NaN
12,13,Zaragoza,38,12,9,17,40,53,-13,45,1.18,NaN,Gabi - 11,Leo Franco,NaN
13,14,Levante,38,12,9,17,41,52,-11,45,1.18,NaN,Felipe Caicedo - 13,Gustavo Munúa,NaN
14,15,Real Sociedad,38,14,3,21,49,66,-17,45,1.18,NaN,"Antoine Griezmann, Xabi Prieto... - 7",Claudio Bravo,NaN
15,16,Getafe,38,12,8,18,49,60,-11,44,1.16,NaN,Manu del Moral - 9,Jordi Codina,NaN
16,17,Mallorca,38,12,8,18,41,56,-15,44,1.16,NaN,Pierre Webó - 11,Dudu Aouate,NaN
17,18,La Coruña,38,10,13,15,31,47,-16,43,1.13,NaN,Adrián López - 8,Daniel Aranzubia,Relegated
18,19,Hércules,38,9,8,21,36,60,-24,35,0.92,NaN,David Trezeguet - 12,Juan Calatayud,Relegated
19,20,Almería,38,6,12,20,36,70,-34,30,0.79,NaN,Pablo Piatti - 8,Diego Alves,Relegated

In [11]:
# List of dataframes from 2010 to 2026
dfs = [
    df_2010_2011, df_2011_2012, df_2012_2013, df_2013_2014,
    df_2014_2015, df_2015_2016, df_2016_2017, df_2017_2018,
    df_2018_2019, df_2019_2020, df_2020_2021, df_2021_2022,
    df_2022_2023, df_2023_2024, df_2024_2025
]

# Standardize column names
for df in dfs:
  df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

# Define expected columns
excepted_columns = [
    "rk", "squad", "mp", "w", "d", "l", "gf", "ga", "gd", "pts"
    "pts/mp", "attendance", "top-scorer", "goalkeeper", "notes",
    "xg", "xga", "xgd", "xgd/90"
]

# Add a seasons column to track the year
years = list(range(2010, 2026))
for df, year in zip(dfs, years):
  df["season"] = year

# Concatenate all seasons (2010 - 2026) into one pandas dataframe
full_data = pd.concat(dfs, ignore_index=True)

In [12]:
# Gives dataset dimensions
print(full_data.shape)

# Shows the first few rows of the data
full_data.head()

(300, 20)

,rk,squad,mp,w,d,l,gf,ga,gd,pts,pts/mp,attendance,top_team_scorer,goalkeeper,notes,season,xg,xga,xgd,xgd/90
0,1,Barcelona,38,30,6,2,95,21,74,96,2.53,NaN,Lionel Messi - 31,Víctor Valdés,→ Champions League via Champions League win,2010,NaN,NaN,NaN,NaN
1,2,Real Madrid,38,29,5,4,102,33,69,92,2.42,NaN,Cristiano Ronaldo - 40,Iker Casillas,→ Champions League via league finish,2010,NaN,NaN,NaN,NaN
2,3,Valencia,38,21,8,9,64,44,20,71,1.87,NaN,Roberto Soldado - 18,Vicente Guaita,→ Champions League via league finish,2010,NaN,NaN,NaN,NaN
3,4,Villarreal,38,18,8,12,54,44,10,62,1.63,NaN,Giuseppe Rossi - 18,Diego López,→ Champions League via league finish,2010,NaN,NaN,NaN,NaN
4,5,Sevilla,38,17,7,14,62,61,1,58,1.53,NaN,Álvaro Negredo - 20,Javi Varas,→ Europa League via league finish,2010,NaN,NaN,NaN,NaN

In [13]:
# Saves Dataframe into a CSV file
full_data.to_csv("la_liga_data_2010_2026.csv", index=False)

# Prints message that dataframe has been saved
print("Data saved successfully!")

Data saved successfully!